### ISSUE TITLE
Capacitor UI not showing after update from 0.4.3 to 0.4.4

### ISSUE THREAD

**Issue by eduardowitter** [gimlet-io/capacitor#124]
[capacitor-645fdf6747-k8cx8_capacitor.log](https://github.com/user-attachments/files/17216371/capacitor-645fdf6747-k8cx8_capacitor.log)

After the update from 0.4.3 to 0.4.4 , the Capacitor UI is not displaying any resources:

![image](https://github.com/user-attachments/assets/a29d3936-f47c-442b-a70a-003a466daa4e)

Capacitor logs are attached.

After rolling back to 0.4.3 I can get the UI working again, so I'm assuming this is related to 0.4.4.

**Comment by hugginsio** [comment]
I am having the same issue with identical log messages on Kubernetes v1.29.3 via Orbstack.

**Comment by ivaylo-mi** [comment]
I have the same issue and added the following to the ServiceAccount
````
- apiGroups:
  - infra.contrib.fluxcd.io
  resources:
  - terraforms
  verbs:
  - get
  - watch
  - list
````
But it didn't help, only the error messages changed to
`level=warning msg="could not marshal event: the server could not find the requested resource"`
