### ISSUE TITLE
Something went wrong:  t.spec.chart is undefined

### ISSUE THREAD

**Issue by CompPhy** [gimlet-io/capacitor#132]
Capacitor appears to be throwing these messages on HelmRelease when chartRef is used in place of chart.  From the flux documentation, they imply that chart and chartRef are kind of mutually exclusive.

Flux is using the chartRef spec as expected, and the CLI tools show that it's deployed properly.  However, capacitor just displays the error about "chart is undefined" instead of the real status.

Here is the relevant documentation link:  https://fluxcd.io/flux/components/helm/helmreleases/#chart-reference

Here is our example that is deploying properly.  **This was previously reported correctly inside capacitor.  This error seems to have started with of the recent releases of capacitor.**

OCIRepository
```
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 5m0s
  url: oci://ghcr.io/netbox-community/netbox-chart/netbox
  ref:
    tag: 5.0.0-beta.52
```

HelmRelease
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: netbox
    namespace: netbox
```

Flux status
```
LAST SEEN                TYPE     REASON             OBJECT                 MESSAGE
23m (x1368 over 4d18h)   Normal   ArtifactUpToDate   OCIRepository/netbox   artifact up-to-date with remote revision: '5.0.0-beta.52@sha256:8c2e5f734841a1bc728be3184a80fc9dfc8e8aadb4040c365dd16bc9ca82fa99'
```
