### ISSUE TITLE
ExternalName services showing all pods

### ISSUE THREAD

**Issue by georgek** [gimlet-io/capacitor#136]
Steps to reproduce:

1. Create an `ExternalName` service in the cluster, e.g.:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: some-external-service
  namespace: default
spec:
  type: ExternalName
  externalName: example.com
```
2. Look in Capacitor UI

Expected behaviour: No pods are shown.
Actual behaviour: All pods in cluster are shown.
