### ISSUE TITLE
docs: document how to add an Ingress in front of Capacitor

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/capacitor#38]

**Comment by sysaeon** [comment]
I had a NetworkPolicy setup for weave-gitops to allow ingress into the flux-system namespace, and just re-used that, changing `app.kubernetes.io/name` to `app.kubernetes.io/instance` for the capacitor label.

This is working, but please note that I'm running the cluster on my LAN. I'm also using a `default-ssl-certificate` for ingress-nginx. I assume the NetworkPolicy would work just the same for HTTPRoute, but I'm not sure.

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: capacitor-ingress
  namespace: flux-system
spec:
  ingressClassName: nginx
  rules:
  - host: gitops.mydomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: capacitor
            port:
              number: 9000
  tls:
    - hosts:
      - gitops.mydomain.com
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: capacitor-ingress
  namespace: flux-system
spec:
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector: {}
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: capacitor
```
