### ISSUE TITLE
feat. add compatibility with ALB as ingress for EKS

### ISSUE THREAD

**Issue by zensqlmonitor** [gimlet-io/capacitor#63]
Hi,

first congratulation for this nice project, that looks fantastic.
Any plan to support AWS ALB as ingress ?

Logs UI is not working and I have continuously this error message :

`Could not process redux event: {"type":"@@redux/INIT4.0.e.f.1.k"}
streamingBackend.js:39  WebSocket connection to 'ws://alb-flux-capacitor-123456789.eu-west-1.elb.amazonaws.com/ws/' failed: 
e.onClose @ streamingBackend.js:39
streamingBackend.js:38 disconnected: 1006.`

Thanks.

**Comment by T0jgli** [comment]
I got the same error using behind a loadbalancer service in k3s. 
```
Could not process redux event: {"type":"@@redux/INITw.p.p.g.d"}
TypeError: Cannot read properties of undefined (reading '0')
```

**Comment by laszlocph** [comment]
The `Could not process redux event: {"type":"@@redux/INIT4.0.e.f.1.k"} ` bit is unrelated, and now handled in: https://github.com/gimlet-io/capacitor/commit/f8d80e55ce6da451b0564fb412b4c667dac048e0#diff-d4bb4bfdb21e67b8faaa157014670a86992d26f3757f734918a12ccf4676a7cbR77

Let me spin up an ALB. Maybe websockets need some love there.

**Comment by marcincuber** [comment]
I have it working fine behind ALB:
```
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: flux-system
  name: capacitor
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-west-2:ACCOUNT_ID:certificate/dfeb4699-f8f1-4cc5-1234
    external-dns.alpha.kubernetes.io/hostname: flux.example.com
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: capacitor
                port:
                  number: 9000
```

**Comment by T0jgli** [comment]
Mine is working now with the latest release

**Comment by zensqlmonitor** [comment]
I confirm the redux event disappeared with the latest release 3.2.
But still receive continuously the following error:

WebSocket connection to 'ws://alb-flux-capacitor-123456789.eu-west-1.elb.amazonaws.com/ws/' failed:  e.onClose @ streamingBackend.js:39 streamingBackend.js:38 disconnected: 1006.

**Comment by zensqlmonitor** [comment]
@laszlocph I tested several ALB configuration s without any success. The issue with ws remains and the logs are not streamed.

**Comment by laszlocph** [comment]
Tried now with this ingress yaml and it works for me.

But I do see that EKS/ALB is has many options I am not saying that it works on all settings.

```
kind: Ingress
metadata:
  namespace: flux-system
  name: capacitor
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: capacitor
                port:
                  number: 9000
```

<img width="1731" alt="image" src="https://github.com/gimlet-io/capacitor/assets/4289031/1693480a-24ac-4d3a-8f96-f8874697e894">
